name: MyDefault

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
    - name: Set commit status
      run: echo "::set-commit-status name='Testss' target_url='https://ci.example.com/tests' status='success' description='All tests passed'"
    
    # - uses: actions/first-interaction@v1
    #   with:
    #     status: "pending"
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     issue-message: "Message that will be displayed on users' first issue"
    #     pr-message: "Message that will be displayed on users' first pull request"

